---
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - vendor/**/*
  - Gemfile
  - Rakefile
  - Vagrantfile
Documentation:
  Enabled: false
ParameterAlignment:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 29
Metrics/BlockLength:
  Max: 32

